### === Настройки ===
@host = http://127.0.0.1:8000
@contentType = application/json

### === Регистрация пользователя ===
POST {{host}}/api/auth/register/
Content-Type: {{contentType}}

{
  "username": "Юля",
  "email": "jyli@mail.ru",
  "password": "123",
  "first_name": "Юля",
  "last_name": "Добро",
  "user_type": "supplier"
}

# данил ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce
# test c59107bec47f61a83b1803bfcff40b52f2ece637
# Юля c80d31d6a1d069fe97d1f3e1460e290fade7d8eb
# связной f8f28de615d8fc9518eba84ba63d394531e94995
### === Логин ===
POST {{host}}/api/auth/login/
Content-Type: {{contentType}}

{
  "username": "admin",
  "password": "admin"
}

### === Добавление адреса доставки (требует токен) ===
POST {{host}}/api/delivery-addresses/
Content-Type: {{contentType}}
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce
# Authorization: Token c59107bec47f61a83b1803bfcff40b52f2ece637

{
  "user": 1,
  "city": "москва",
  "street": "Александра Пушкина ",
  "house": "14",
  "apartment": "10"
}

### === Получение профиля (требует токен) ===
GET {{host}}/api/auth/profile/
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

### === Получение списка товаров ===
GET {{host}}/api/products/

### === Получение списка категорий ===
GET {{host}}/api/categories/

### === Получение содержимого корзины (требует токен) ===
GET {{host}}/api/basket/
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

### === Добавление товара в корзину (требует токен) ===
POST {{host}}/api/basket/add/
Content-Type: {{contentType}}
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

{
  "product_id": 2,
  "quantity": 1
}

### === Оформление заказа (требует токен) ===
POST {{host}}/api/orders/create/
Content-Type: {{contentType}}
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

{
  "delivery_address_id": 11
}

### === Получение списка заказов (требует токен) ===
GET {{host}}/api/orders/
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

### === Получение списка поставщиков (публичный) ===
GET {{host}}/api/suppliers/

### === обновление колличества товара 
PUT {{host}}/api/basket/update/10/
Content-Type: {{contentType}}
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

{
  "quantity": 5
}
###=== удаление из корзины  
DELETE {{host}}/api/basket/remove/17/
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce


### ===Удалить адрес доствки 
DELETE {{host}}/api/delivery-addresses/1/
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

### === API-эндпоинт, чтобы поставщик мог изменить это поле через API.
PUT {{host}}/api/supplier/toggle-accepts-orders/
Content-Type: {{contentType}}
Authorization:Token f8f28de615d8fc9518eba84ba63d394531e94995

{
  "accepts_orders": false
}

### === Получать список оформленных заказов 
GET {{host}}/api/supplier/orders/
Authorization: Token f8f28de615d8fc9518eba84ba63d394531e94995


### --  API-эндпоинт, через который поставщик сможет загружать/обновлять свои товары в базу данных через API
POST {{host}}/api/supplier/upload-price/
Content-Type: application/json
Authorization: Token f8f28de615d8fc9518eba84ba63d394531e94995

{
  "categories": [
    {
      "id": 224,
      "name": "яблоко"
    }
  ],
  "goods": [
    {
      "id": 4216292,
      "category": 224,
      "model": "apple/iphone/xs-max",
      "name": "Смартфон Apple iPhone XS Max 512GB (золотистый)",
      "price": 110000,
      "price_rrc": 116990,
      "quantity": 14,
      "parameters": {
        "Диагональ (дюйм)": 6.5,
        "Разрешение (пикс)": "2688x1242",
        "Встроенная память (Гб)": 512,
        "Цвет": "золотистый"
      }
    }
  ]
}


###=== изменение статуса заказа для АДМИНА
PUT {{host}}/api/orders/1/status/
Content-Type: application/json
Authorization: Token d69a3c83a6ee8184807758225e5a48f93477307c

{
  "status": "new"
}