### === Настройки ===
@host = http://127.0.0.1:8000
@contentType = application/json

### === Регистрация пользователя ===
POST {{host}}/api/auth/register/
Content-Type: {{contentType}}

{
  "username": "Данил",
  "email": "danil@mail.ru",
  "password": "123",
  "first_name": "Danil",
  "last_name": "Dobr",
  "user_type": "client"
}

# данил ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce
# test c59107bec47f61a83b1803bfcff40b52f2ece637
### === Логин ===
POST {{host}}/api/auth/login/
Content-Type: {{contentType}}

{
  "username": "Данил",
  "password": "123"
}

### === Добавление адреса доставки (требует токен) ===
POST {{host}}/api/delivery-addresses/
Content-Type: {{contentType}}
Authorization: Token c59107bec47f61a83b1803bfcff40b52f2ece637
# Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

{
  "user": 1,
  "city": "Губкинский",
  "street": "Александра Пушкина ",
  "house": "14",
  "apartment": "10"
}

### === Получение профиля (требует токен) ===
GET {{host}}/api/auth/profile/
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

### === Получение списка товаров ===
GET {{host}}/api/products/

### === Получение списка категорий ===
GET {{host}}/api/categories/

### === Получение содержимого корзины (требует токен) ===
GET {{host}}/api/basket/
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

### === Добавление товара в корзину (требует токен) ===
POST {{host}}/api/basket/add/
Content-Type: {{contentType}}
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

{
  "product_id": 3,
  "quantity": 20
}

### === Оформление заказа (требует токен) ===
POST {{host}}/api/orders/create/
Content-Type: {{contentType}}
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

{
  "delivery_address_id": 1
}

### === Получение списка заказов (требует токен) ===
GET {{host}}/api/orders/
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

### === Получение списка поставщиков (публичный) ===
GET {{host}}/api/suppliers/

### === обновление колличества товара 
PUT {{host}}/api/basket/update/10/
Content-Type: {{contentType}}
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce

{
  "quantity": 5
}
###=== удаление из корзины  

DELETE {{host}}/api/basket/remove/9/
Authorization: Token ea3f6a32efa7007801b3bf1f7fbb5f672a0277ce